spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/camunda-db
#    username: root
#    password: root
  datasource.url: jdbc:h2:file:./camunda-h2-database
  h2:
    console.enabled: true
camunda.bpm:
  authorization:
    enabled: true

#  admin-user:
#    id: demo
#    password: demo
# Camunda Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: http://localhost:9001/auth/realms/master
  keycloakAdminUrl: http://localhost:9001/auth/admin/realms/master
  clientId: camunda-identity-service
  clientSecret: 5qBO5GmHXUE2PxIO04JaZRin4mA3PK3g
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
#  administratorUserId: admin
  disableSSLCertificateValidation: true

keycloak:
  # SSO Authentication requests. Send by application as redirect to the browser
  url.auth: ${KEYCLOAK_URL_AUTH:http://localhost:9001}
  # SSO Token requests. Send from the application to Keycloak
  url.token: ${KEYCLOAK_URL_TOKEN:http://localhost:9001}
  # Keycloak access for the Identity Provider plugin.
  url.plugin: ${KEYCLOAK_URL_PLUGIN:https://localhost:9001}

  # Keycloak Camunda Identity Client
  client.id: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
  client.secret: ${KEYCLOAK_CLIENT_SECRET:5qBO5GmHXUE2PxIO04JaZRin4mA3PK3g}

  spring.security.oauth2:
    client:
      registration:
        keycloak:
          provider: keycloak
          client-id: ${keycloak.client.id}
          client-secret: ${keycloak.client.secret}
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope: openid, profile, email
      provider:
        keycloak:
          issuer-uri: ${keycloak.url.auth}/auth/realms/master
          authorization-uri: ${keycloak.url.auth}/auth/realms/master/protocol/openid-connect/auth
          user-info-uri: ${keycloak.url.auth}/auth/realms/master/protocol/openid-connect/userinfo
          token-uri: ${keycloak.url.token}/auth/realms/master/protocol/openid-connect/token
          jwk-set-uri: ${keycloak.url.token}/auth/realms/master/protocol/openid-connect/certs
          # set user-name-attribute one of:
          # - sub                -> default; using keycloak ID as camunda user ID
          # - email              -> useEmailAsCamundaUserId=true
          # - preferred_username -> useUsernameAsCamundaUserId=true
          user-name-attribute: preferred_username

# Camunda Rest API
rest.security:
  enabled: true
  provider: keycloak
  required-audience: camunda-rest-api